### ISSUE TITLE
Broken Dividends Endpoint since IEX 12/01 upgrade

### ISSUE THREAD

**Issue by rmantovani** [WojciechZankowski/iextrading4j#105] opened 2020-12-18 22:16 UTC
**Describe the bug**
Dividends endpoint and many others endpoint broken since IEX 12/01/2020 upgrade.

Caused by: com.fasterxml.jackson.databind.JsonMappingException: Invalid value for Year (valid values -999999999 - 999999999): 4203587259 (through reference chain: java.util.ArrayList[0]->pl.zankowski.iextrading4j.api.stocks.v1.Dividends["date"])

**To Reproduce**

// symbol = AAPL 
final List<pl.zankowski.iextrading4j.api.stocks.v1.Dividends> dividends = cloudClient.executeRequest(new DividendsRequestBuilder()
                            .withSymbol(syb.getSymbol())
                            .withDividendRange(DividendRange.FIVE_YEARS)
                            .build());
**Expected behavior**
return java object

**Comment by compengi** [comment] 2020-12-22 16:03
I had the same problem lately. As a workaround, I had to reimplement the Dividends endpoint to treat "data" as Long. The problem is that the "date" is in epoch milliseconds resolution and jackson-databinder tries to call LocalDate.ofEpochDay() which causes the above exception.

To solve this problem, I suggest treating "date" as Long value similar to the "latestUpdate" field in Quote.

**Comment by JoseMariaBernad** [comment] 2020-12-23 06:05
I have a fix for this that does not break your current code in your projects that depend on iextrading4j. I will make a pull request soon.

**Comment by JoseMariaBernad** [comment] 2020-12-23 06:32
The pull request is created https://github.com/WojciechZankowski/iextrading4j/pull/106

Let's see if @WojciechZankowski has time to review.

I wish you all a Merry Christmas :-)

**Comment by WojciechZankowski** [comment] 2021-01-09 18:06
@rmantovani 

Issue fixed in the newest versions of the library:
```
<dependency>
	<groupId>pl.zankowski</groupId>
	<artifactId>iextrading4j-all</artifactId>
	<version>3.4.2</version>
</dependency>
```

One thing, I see that ```date``` field type changed from LocalDate to Long and represents timestamp according to the specification. On top of it I don't really see any stocks where ```date``` field is returned.

**Closed by WojciechZankowski** 2021-01-09 18:06 UTC
